name = "gemini-app"
compatibility_date = "2024-01-01"

[env.production]
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
[build]
command = "npm run build"
cwd = "."
publish = "dist"

# Environment variables for Cloudflare Pages
[vars]
NODE_ENV = "production"

# Build configuration
[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--prefer-offline --no-audit --progress=false"